[project]
name = "janimproj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dowhen>=0.1.0",
    "janim[gui]>=3.10.2",
    "numpy>=2.4.1",
    "pydantic>=2.12.5",
]
